---
- name: Running "apt-get update"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400

- name: Running "apt-get upgrade"
  ansible.builtin.apt:
    name: "*"
    state: latest
