---
- name: Running "apt-get update"
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Running "apt-get upgrade"
  ansible.builtin.apt:
    name: "*"
    state: latest
