---
- name: Install apt packages
  ansible.builtin.include_tasks: apt-upgrade.yml
  when: ansible_facts['os_family'] in ['Debian'] 

- name: Install dnf packages
  ansible.builtin.include_tasks: dnf-upgrade.yml
  when: ansible_facts['os_family'] in ['RedHat', 'CentOS']
