---
- name: Disable swap
  ansible.builtin.include_tasks:
    file: swap.yml
  tags: ['linux', 'always', 'swap']

- name: Populate /etc/hosts
  ansible.builtin.include_tasks:
    file: etc_hosts.yml
  tags: ['linux', 'always', 'etc_hosts']

- name: Create service users
  ansible.builtin.include_tasks:
    file: users.yml
  tags: ['linux', 'always', 'users']
