---
- name: Add Docker repository
  get_url:
    url: "{{ docker_repo }}"
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Update package cache
  ansible.builtin.package:
    update_cache: true

- name: Ensure yum-utils and dnf-plugins-core are installed
  ansible.builtin.package:
    name:
      - yum-utils
      - dnf-plugins-core
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present