---
- name: Inform about minikube configuring
  debug:
    msg: "Configuring minikube. This may take time depending on your connection speed."

- name: Configure minikube
  ansible.builtin.shell: |
    minikube start --vm-driver="{{ minikube_vm_driver }}" "{{ minikube_stable_parameters }}"

- name: Create systemd service file for kubectl
  ansible.builtin.copy:
    dest: /etc/systemd/system/kubectl.service
    content: "{{ kubectl_service_content }}"

- name: Create systemd service for minikube
  ansible.builtin.copy:
    dest: /etc/systemd/system/minikube.service
    content: "{{ minikube_service_content }}"

- name: Start and enable Kubectl service
  ansible.builtin.systemd:
    name: kubectl
    state: started
    enabled: true

- name: Start and enable Minikube service
  ansible.builtin.systemd:
    name: minikube
    state: started
    enabled: true