---

- name: Check if minikube exists
  ansible.builtin.stat:
    path: /usr/local/bin/minikube
  register: minikube_existion

- name: Ask handler to install minikube if not exists
  ansible.builtin.debug: 
    msg: "Minikube not installed, this may take some time."
  when: not minikube_existion.stat.exists
  notify: Install minikube

- name: Check if kubectl exists
  ansible.builtin.stat:
    path: /usr/local/bin/kubectl
  register: kubectl_existion

- name: Ask handler to install kubectl if not exists
  ansible.builtin.debug:
    msg: "Kubectl not installed, this may take some time."
  when: not kubectl_existion.stat.exists
  notify: Install kubectl