---
- name: Install apt packages
  ansible.builtin.include_tasks: apt-dependencies.yml
  when: ansible_facts['os_family'] in ['Debian']

- name: Install dnf packages
  ansible.builtin.include_tasks: dnf-dependencies.yml
  when: ansible_facts['os_family'] in ['RedHat', 'CentOS']

- name: Setup docker preferences
  ansible.builtin.include_tasks: docker-preferences.yml

- name: Install services
  ansible.builtin.include_tasks: kube-install.yml

- name: Set preferences
  ansible.builtin.include_tasks: kube-preferences.yml
