---
- include_tasks: apt-dependencies.yml
  when: ansible_facts['os_family'] in ['Debian']

- include_tasks: minikube-dnf-dependencies.yml
  when: ansible_facts['os_family'] in ['RedHat', 'CentOS']

- include_tasks: docker-preferences.yml

- include_tasks: kube-install.yml

- include_tasks: kube-preferences.yml
