---
- name: Update APT package index
  ansible.builtin.apt:
    update_cache: true

- name: Install required packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      # - ca-certificate #idk it gives me 3rr0r
      - curl
      - software-properties-common
      - conntrack
      - docker.io   # Should I make it independent?..
    state: present

- name: Add user to Docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    # append: true

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

# - name: Install Docker
#   ansible.builtin.package:
#     name:
      

- name: Download kubectl binary
  shell: |
    curl -LO "{{ kubectl_repo }}"
  args:
    chdir: /usr/local/bin

- name: Make it executable
  file: dest=/usr/local/bin/kubectl mode=a+x


