---
- name: Ensure yum-utils and dnf-plugins-core are installed
  package:
    name:
      - yum-utils
      - dnf-plugins-core
    state: present

- name: Add Docker repository
  get_url:
    url: "{{ docker_repo }}"
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Update package cache
  