---
- name: etc_hosts | Populate inventory into /etc/hosts
  ansible.builtin.blockinfile:
    dest: "/etc/hosts"
    block: |-
      {% for item in groups['elk'] %}
      {{ hostvars[item]['ip'] }} {{ item }}.{{ base_fqdn }} {{ item }}
      {% endfor %}
    state: present
    mode: '0644'
    backup: true
  become: true
