---
# Some repositories
docker_repo: "https://download.docker.com/linux/centos/docker-ce.repo"
kubectl_repo: "https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubectl"
minikube_repo: "https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"

# Service destination & systemd paths
kubectl_path: "/usr/bin/kubectl"
minikube_path: "/usr/bin/minikube"
systemd_config_path: "/etc/systemd/system"

# Minikube parameters you can change depending on your host configuration
minikube_stable_parameters: "--force --vm-driver=docker --memory=1900mb --ports=8443:8443 --network=bridge"
minikube_start_parameters: "--force --wait=all"
