---

- name: Create systemd service for minikube
  ansible.builtin.template:
    src: "{{ role_path }}/templates/minikube.service.j2"
    dest: "{{ systemd_config_path }}/minikube.service"
  become: true

- name: Inform about minikube configuring
  ansible.builtin.debug:
    msg: "Configuring minikube. This may take time depending on your connection speed."

- name: Configure minikube
  ansible.builtin.command:
    cmd: "minikube start {{ minikube_stable_parameters }}"

- name: Start and enable Minikube service
  ansible.builtin.systemd:
    name: minikube
    state: started
    enabled: true
  become: true
