---
- name: Install minikube
  ansible.builtin.get_url:
    url: "{{ minikube_repo }}"
    dest: "{{ minikube_path }}"
    mode: '0755'
  args:
    creates: "{{ minikube_path }}"

- name: Install kubectl
  ansible.builtin.get_url:
    url: "{{ kubectl_repo }}"
    dest: "{{ kubectl_path }}"
    mode: '0755'
  args:
    creates: "{{ kubectl_path }}"
    