---
- name: Install minikube
  ansible.builtin.shell: |
    curl -Lo minikube "{{ minikube_repo }}" -o "{{ minikube_path }}"
    chmod +x "{{ minikube_path }}"
  args:
    creates: "{{ minikube_path }}"

- name: Install kubectl
  ansible.builtin.shell: |
    curl -Lo "{{ kubectl_repo }}" -o "{{ kubectl_path }}"
    chmod +x "{{ kubectl_path }}"
  args:
    creates: "{{ kubectl_path }}"