---
- name: Update package index
  ansible.builtin.package:
    update_cache: true
  become: true

- name: Install required packages
  ansible.builtin.package:
    name: >
      {{
        [
          'apt-transport-https',
          'ca-certificates',
          'curl',
          'software-properties-common',
          'conntrack'
        ]
        + ([ 'docker.io' ] if vm_driver in ['docker','none'] else [])
      }}
    state: present
  become: true
